[theme]
# Primary accent color for interactive elements.
primaryColor = "#FFC109"

# Background color for the main content area.
backgroundColor = "#191D2B"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#262730"

# Color used for almost all text.
textColor = "#fff"