[theme]
# Primary accent color for interactive elements.
primaryColor = "#002A83"

# Background color for the main content area.
backgroundColor = "#FFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#31333F"